// Every `expected` array lists row values only (column order/name doesn't
// matter — see compareResults.js). Verified against the real seed data in
// db.js with a standalone sql.js harness before being committed here.

export const PHASES = [
  {
    id: 'coffee-basics',
    title: 'Coffee Basics',
    subtitle: 'menu_items',
    tables: ['menu_items'],
    description: 'The 10-level basics track: SELECT, WHERE, comparisons, AND/OR/LIKE/BETWEEN/IN.',
    challenges: [
      {
        id: 'p1-1',
        title: 'See the Menu',
        prompt: 'Show every item on the café menu.',
        hint: 'SELECT * FROM the table.',
        lesson: [
          "SELECT is the SQL keyword you use any time you want to read data out of a table — think of it as saying 'show me...'",
          "The asterisk (*) is a wildcard meaning 'every column'. Instead of typing out id, name, category, price, calories one by one, * grabs them all.",
          'FROM menu_items tells the database which table to read from — this café keeps its menu in a table called menu_items.',
          "Put it together: SELECT * FROM menu_items; returns every column, for every row, in the menu_items table — the whole menu, exactly as it's stored.",
        ],
        starterQuery: '',
        type: 'select',
        intro: [
          { speaker: 'kiko', text: 'Welcome to your first day at the café, Mini!' },
          { speaker: 'mini', text: "Thank you so much, Kiko! I wanted to know — how can I see the **whole menu**?" },
          { speaker: 'kiko', text: 'Great question, Mini! We are going to use **SELECT *** for that.' },
          { speaker: 'kiko', text: "**SELECT * FROM** a table shows you every row and every column in it. Let's give it a try!" },
        ],
        expected: [
          [1, 'Latte', 'coffee', 4.5, 190],
          [2, 'Espresso', 'coffee', 3.0, 5],
          [3, 'Cold Brew', 'coffee', 5.25, 5],
          [4, 'Cappuccino', 'coffee', 4.75, 120],
          [5, 'Mocha', 'coffee', 5.0, 290],
          [6, 'Muffin', 'bakery', 3.0, 420],
          [7, 'Croissant', 'bakery', 3.25, 270],
          [8, 'Espresso Beans (1kg)', 'retail', 18.0, null],
          [9, 'Gift Card', 'retail', 25.0, null],
          [10, 'Caramel Latte', 'coffee', 5.5, 210],
          [11, 'Green Tea', 'tea', 3.5, 0],
          [12, 'Chai Latte', 'tea', 4.75, 180],
          [13, 'Earl Grey', 'tea', 3.75, 0],
        ],
      },
      {
        id: 'p1-2',
        title: 'Name & Price',
        prompt: "Your cashier only needs the item name and price for every menu item.",
        hint: 'List specific column names instead of using *.',
        lesson: [
          'Once you can already pull an entire table with SELECT *, the next step is choosing exactly which columns you actually need.',
          'List the column names you want, separated by commas, right after SELECT — order matters here, since the results come back in the order you list them.',
          'SELECT name, price FROM menu_items; ignores category and calories entirely and returns only two columns: the item\'s name and its price.',
          'This matters in real apps: pulling only the columns you need keeps results smaller and faster, especially on big tables.',
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        intro: [
          { speaker: 'kiko', text: 'Great Job Mini!' },
          { speaker: 'mini', text: "Thank you so much, Kiko!" },
          { speaker: 'kiko', text: 'Now we are going to learn if you want to see **specific columns**. Only enter the column names you want.' },
          ],
        expected: [
          ['Latte', 4.5],
          ['Espresso', 3.0],
          ['Cold Brew', 5.25],
          ['Cappuccino', 4.75],
          ['Mocha', 5.0],
          ['Muffin', 3.0],
          ['Croissant', 3.25],
          ['Espresso Beans (1kg)', 18.0],
          ['Gift Card', 25.0],
          ['Caramel Latte', 5.5],
          ['Green Tea', 3.5],
          ['Chai Latte', 4.75],
          ['Earl Grey', 3.75],
        ],
      },
      {
        id: 'p1-3',
        title: 'Top of the Menu',
        prompt: 'Your menu has a lot of items — show only the first 5.',
        hint: 'Add LIMIT to the end of your query.',
        lesson: [
          "Sometimes you don't want every row — just a preview. LIMIT caps how many rows come back.",
          "LIMIT always goes at the very end of the query, after everything else, and takes a plain number: LIMIT 5 means 'stop after 5 rows'.",
          'SELECT * FROM menu_items LIMIT 5; still reads the whole table structurally, but the database only sends back the first 5 rows it finds.',
          "Because there's no ORDER BY yet, 'first 5' just means whatever order SQLite happens to store them in — here, that's insertion order (ids 1 through 5).",
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [
          [1, 'Latte', 'coffee', 4.5, 190],
          [2, 'Espresso', 'coffee', 3.0, 5],
          [3, 'Cold Brew', 'coffee', 5.25, 5],
          [4, 'Cappuccino', 'coffee', 4.75, 120],
          [5, 'Mocha', 'coffee', 5.0, 290],
        ],
      },
      {
        id: 'p1-4',
        title: 'Coffee Only',
        prompt: 'A customer only wants coffee — show every item in the coffee category.',
        hint: 'Use WHERE to filter by category.',
        lesson: [
          'WHERE is how you filter rows — only rows where the condition is true make it into the result.',
          "Comparing text needs quotes: WHERE category = 'coffee' checks the category column against the exact string 'coffee'.",
          "SELECT * FROM menu_items WHERE category = 'coffee'; scans every row, keeps the ones where category equals 'coffee', and throws away the rest.",
          "WHERE runs before your results are returned, so filtering happens on the full table every time — it's not applied after the fact.",
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [
          [1, 'Latte', 'coffee', 4.5, 190],
          [2, 'Espresso', 'coffee', 3.0, 5],
          [3, 'Cold Brew', 'coffee', 5.25, 5],
          [4, 'Cappuccino', 'coffee', 4.75, 120],
          [5, 'Mocha', 'coffee', 5.0, 290],
          [10, 'Caramel Latte', 'coffee', 5.5, 210],
        ],
      },
      {
        id: 'p1-5',
        title: 'Under $5',
        prompt: 'A student only has $5 — find every menu item that costs less than $5.',
        hint: 'Use a comparison operator like < on price.',
        lesson: [
          'WHERE isn\'t limited to equality — you can use comparison operators like <, >, <=, >=, and != too.',
          'Since price is a number column, no quotes are needed: WHERE price < 5 compares it directly against the number 5.',
          'SELECT * FROM menu_items WHERE price < 5; keeps only rows where the price column is strictly less than 5.',
          'Watch the boundary: an item priced at exactly $5.00 would NOT show up here, because < is strictly less-than, not less-than-or-equal.',
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [
          [1, 'Latte', 'coffee', 4.5, 190],
          [2, 'Espresso', 'coffee', 3.0, 5],
          [4, 'Cappuccino', 'coffee', 4.75, 120],
          [6, 'Muffin', 'bakery', 3.0, 420],
          [7, 'Croissant', 'bakery', 3.25, 270],
          [11, 'Green Tea', 'tea', 3.5, 0],
          [12, 'Chai Latte', 'tea', 4.75, 180],
          [13, 'Earl Grey', 'tea', 3.75, 0],
        ],
      },
      {
        id: 'p1-6',
        title: 'Cheap Coffee',
        prompt: 'Someone wants cheap coffee — find coffee drinks costing less than $6.',
        hint: 'Combine two conditions with AND.',
        lesson: [
          'AND lets you combine two conditions — a row only makes it into the results if BOTH sides are true.',
          "WHERE category = 'coffee' AND price < 6 first checks the category, then checks the price; a row has to pass both checks.",
          "SELECT * FROM menu_items WHERE category = 'coffee' AND price < 6; narrows the whole menu down to just the coffee drinks, then narrows again to the ones under $6.",
          "Order of the two conditions around AND doesn't matter — category = 'coffee' AND price < 6 gives the exact same result as price < 6 AND category = 'coffee'.",
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [
          [1, 'Latte', 'coffee', 4.5, 190],
          [2, 'Espresso', 'coffee', 3.0, 5],
          [3, 'Cold Brew', 'coffee', 5.25, 5],
          [4, 'Cappuccino', 'coffee', 4.75, 120],
          [5, 'Mocha', 'coffee', 5.0, 290],
          [10, 'Caramel Latte', 'coffee', 5.5, 210],
        ],
      },
      {
        id: 'p1-7',
        title: 'Tea or Coffee',
        prompt: 'A customer likes either tea or coffee — show every item in either category.',
        hint: 'Combine two conditions with OR.',
        lesson: [
          'OR is the opposite of AND — a row makes it in if EITHER side is true, not both.',
          "WHERE category = 'tea' OR category = 'coffee' keeps a row if its category matches tea, matches coffee, or (impossible here, but conceptually) both.",
          "SELECT * FROM menu_items WHERE category = 'tea' OR category = 'coffee'; returns every tea item plus every coffee item, combined into one result set.",
          "A common mix-up: AND would return nothing useful here, since no single row can have category equal to both 'tea' and 'coffee' at once — that's exactly why this needs OR.",
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [
          [1, 'Latte', 'coffee', 4.5, 190],
          [2, 'Espresso', 'coffee', 3.0, 5],
          [3, 'Cold Brew', 'coffee', 5.25, 5],
          [4, 'Cappuccino', 'coffee', 4.75, 120],
          [5, 'Mocha', 'coffee', 5.0, 290],
          [10, 'Caramel Latte', 'coffee', 5.5, 210],
          [11, 'Green Tea', 'tea', 3.5, 0],
          [12, 'Chai Latte', 'tea', 4.75, 180],
          [13, 'Earl Grey', 'tea', 3.75, 0],
        ],
      },
      {
        id: 'p1-8',
        title: 'Fuzzy Memory',
        prompt: 'A customer forgot the full name of a drink — they only remember it starts with "Car". Find it.',
        hint: 'Use LIKE with a % wildcard.',
        lesson: [
          "LIKE is for pattern matching text instead of exact matches — perfect for 'starts with', 'contains', or 'ends with' searches.",
          "% is the wildcard inside a LIKE pattern — it matches any run of characters (including none). 'Car%' means 'starts with Car, then anything'.",
          "SELECT * FROM menu_items WHERE name LIKE 'Car%'; checks the name column against that pattern and keeps only matches — here, that's 'Caramel Latte'.",
          "If you wanted 'contains' instead of 'starts with', you'd wrap the wildcard on both sides: '%Car%'.",
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [[10, 'Caramel Latte', 'coffee', 5.5, 210]],
      },
      {
        id: 'p1-9',
        title: 'Middle of the Menu',
        prompt: 'Your manager wants medium-priced drinks — find items costing between $4 and $8.',
        hint: 'Use BETWEEN ... AND ...',
        lesson: [
          'BETWEEN ... AND ... is shorthand for a range check — it\'s equivalent to writing price >= 4 AND price <= 8, just more readable.',
          'Both ends are inclusive: BETWEEN 4 AND 8 includes items priced at exactly $4.00 and exactly $8.00, not just the values strictly in between.',
          'SELECT * FROM menu_items WHERE price BETWEEN 4 AND 8; keeps every menu item priced from $4 to $8, inclusive on both sides.',
          'BETWEEN works on dates and text too, not just numbers — it\'s a general range tool, not just for prices.',
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [
          [1, 'Latte', 'coffee', 4.5, 190],
          [3, 'Cold Brew', 'coffee', 5.25, 5],
          [4, 'Cappuccino', 'coffee', 4.75, 120],
          [5, 'Mocha', 'coffee', 5.0, 290],
          [10, 'Caramel Latte', 'coffee', 5.5, 210],
          [12, 'Chai Latte', 'tea', 4.75, 180],
        ],
      },
      {
        id: 'p1-10',
        title: 'Breakfast Menu',
        prompt: "You're making a breakfast menu — show only coffee, tea, and bakery items.",
        hint: 'Use IN with a list of categories.',
        lesson: [
          'IN lets you check a column against a whole list of acceptable values in one shot, instead of chaining several ORs together.',
          "WHERE category IN ('coffee', 'tea', 'bakery') is equivalent to category = 'coffee' OR category = 'tea' OR category = 'bakery' — just shorter and easier to read.",
          "SELECT * FROM menu_items WHERE category IN ('coffee', 'tea', 'bakery'); keeps rows whose category matches ANY value in that list, and drops 'retail' items entirely.",
          'IN scales well — checking against 10 categories with IN is just as clean as checking against 3.',
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [
          [1, 'Latte', 'coffee', 4.5, 190],
          [2, 'Espresso', 'coffee', 3.0, 5],
          [3, 'Cold Brew', 'coffee', 5.25, 5],
          [4, 'Cappuccino', 'coffee', 4.75, 120],
          [5, 'Mocha', 'coffee', 5.0, 290],
          [6, 'Muffin', 'bakery', 3.0, 420],
          [7, 'Croissant', 'bakery', 3.25, 270],
          [10, 'Caramel Latte', 'coffee', 5.5, 210],
          [11, 'Green Tea', 'tea', 3.5, 0],
          [12, 'Chai Latte', 'tea', 4.75, 180],
          [13, 'Earl Grey', 'tea', 3.75, 0],
        ],
      },
    ],
  },
  {
    id: 'brewing-skills',
    title: 'Brewing Skills',
    subtitle: 'menu_items',
    tables: ['menu_items'],
    description: 'The 7-level intermediate track: ORDER BY, DISTINCT, COUNT, AVG, MAX/MIN, GROUP BY, and HAVING.',
    challenges: [
      {
        id: 'p2-1',
        title: 'Cheapest First',
        prompt: 'Customers want the cheapest drinks first — sort the menu from cheapest to most expensive.',
        hint: 'ORDER BY price.',
        lesson: [
          "ORDER BY controls the order results come back in — without it, row order is essentially whatever the database feels like.",
          'By default ORDER BY sorts ascending (smallest/earliest first): ORDER BY price sorts from the cheapest item to the most expensive.',
          'SELECT * FROM menu_items ORDER BY price; returns the entire menu, but now sorted cheapest-to-priciest.',
          'To flip the direction, add DESC after the column — ORDER BY price DESC would sort most expensive first.',
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [
          [2, 'Espresso', 'coffee', 3.0, 5],
          [6, 'Muffin', 'bakery', 3.0, 420],
          [7, 'Croissant', 'bakery', 3.25, 270],
          [11, 'Green Tea', 'tea', 3.5, 0],
          [13, 'Earl Grey', 'tea', 3.75, 0],
          [1, 'Latte', 'coffee', 4.5, 190],
          [4, 'Cappuccino', 'coffee', 4.75, 120],
          [12, 'Chai Latte', 'tea', 4.75, 180],
          [5, 'Mocha', 'coffee', 5.0, 290],
          [3, 'Cold Brew', 'coffee', 5.25, 5],
          [10, 'Caramel Latte', 'coffee', 5.5, 210],
          [8, 'Espresso Beans (1kg)', 'retail', 18.0, null],
          [9, 'Gift Card', 'retail', 25.0, null],
        ],
      },
      {
        id: 'p2-2',
        title: 'What Categories Exist',
        prompt: "You forgot which categories the café sells — show each menu category only once.",
        hint: 'Use DISTINCT.',
        lesson: [
          "menu_items has one row per item, so a plain SELECT category would repeat 'coffee' six times, 'tea' three times, and so on.",
          'DISTINCT removes duplicate rows from the result, keeping only the unique values that appear.',
          'SELECT DISTINCT category FROM menu_items; collapses all those repeats down to one row per unique category value.',
          "DISTINCT applies to the whole selected row, not just one column — with multiple columns selected, it keeps unique combinations, not unique values per column.",
        ],
        starterQuery: 'SELECT category FROM menu_items;',
        type: 'select',
        expected: [['coffee'], ['bakery'], ['retail'], ['tea']],
      },
      {
        id: 'p2-3',
        title: 'How Many Items',
        prompt: 'How many menu items do you sell in total?',
        hint: 'Use COUNT(*).',
        lesson: [
          'COUNT(*) is an aggregate function — instead of returning rows, it returns a single number summarizing them.',
          'COUNT(*) specifically counts every row, regardless of whether any column has NULLs in it.',
          "SELECT COUNT(*) FROM menu_items; doesn't return the menu itself at all — it returns one row, one number: how many rows are in the table.",
          "Aggregate functions like this are the foundation for reporting-style questions — 'how many', 'what's the total', 'what's the average'.",
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [[13]],
      },
      {
        id: 'p2-4',
        title: 'Average Price',
        prompt: "What's the average menu price?",
        hint: 'Use AVG(price).',
        lesson: [
          'AVG(price) is another aggregate function — it adds up every value in the price column and divides by how many rows there are.',
          'Like COUNT(*), AVG(price) collapses the whole table into a single summary row — you won\'t see individual item prices in the output.',
          'SELECT AVG(price) FROM menu_items; computes the mean price across all 13 menu items in one step, no manual math required.',
          "Aggregate functions ignore NULL values automatically — if a row's price were NULL, AVG would skip it rather than treating it as zero.",
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [[6.865]],
      },
      {
        id: 'p2-5',
        title: 'Highest and Lowest',
        prompt: 'Find the price of the most expensive item and the cheapest item, in one query.',
        hint: 'Use MAX(price) and MIN(price) together.',
        lesson: [
          'MAX and MIN are aggregate functions that find the largest and smallest value in a column, respectively.',
          'You can use more than one aggregate function in the same SELECT — SQL computes each one independently over the same rows.',
          "SELECT MAX(price), MIN(price) FROM menu_items; returns one row with two numbers: the priciest item's price and the cheapest item's price, side by side.",
          "This only tells you the price values themselves, not which items they belong to — for that you'd need to also select name and use ORDER BY + LIMIT instead.",
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [[25.0, 3.0]],
      },
      {
        id: 'p2-6',
        title: 'Items per Category',
        prompt: 'Your supplier asks: how many items are in each category?',
        hint: 'GROUP BY category with COUNT(*).',
        lesson: [
          'GROUP BY changes how aggregate functions work — instead of summarizing the whole table at once, it summarizes each group separately.',
          'GROUP BY category buckets every row by its category value first — all the coffee rows together, all the tea rows together, and so on.',
          'SELECT category, COUNT(*) FROM menu_items GROUP BY category; then runs COUNT(*) once per bucket, giving you one result row per category with its own item count.',
          "Any column you SELECT alongside an aggregate function generally needs to be part of the GROUP BY — that's what makes 'category' safe to select here even though COUNT(*) is a per-group summary.",
        ],
        starterQuery: 'SELECT * FROM menu_items;',
        type: 'select',
        expected: [
          ['bakery', 2],
          ['coffee', 6],
          ['retail', 2],
          ['tea', 3],
        ],
      },
      {
        id: 'p2-7',
        title: 'Big Categories Only',
        prompt: 'Some categories are tiny — show only categories with more than 5 items.',
        hint: 'GROUP BY category, then HAVING COUNT(*) > 5.',
        lesson: [
          "WHERE filters individual rows before grouping happens — but you can't use WHERE to filter on an aggregate result like COUNT(*), because that value doesn't exist yet at that stage.",
          "HAVING is WHERE's counterpart for after grouping — it filters the grouped results themselves, based on the aggregate values.",
          'GROUP BY category HAVING COUNT(*) > 5 first buckets rows by category and counts each bucket, then keeps only the buckets where that count is greater than 5.',
          "SELECT category, COUNT(*) FROM menu_items GROUP BY category HAVING COUNT(*) > 5; — with 6 coffee items and no other category reaching 6, only 'coffee' survives the HAVING filter.",
        ],
        starterQuery: 'SELECT category, COUNT(*) FROM menu_items GROUP BY category;',
        type: 'select',
        expected: [['coffee', 6]],
      },
    ],
  },
  {
    id: 'game-zone',
    title: 'Game Zone Unlocked',
    subtitle: 'menu_items, orders, customers, reviews',
    tables: ['orders', 'customers', 'reviews'],
    description: 'Level up to subqueries, GROUP BY / HAVING, and EXISTS.',
    challenges: [
      {
        id: 'p3-1',
        title: 'Above Average',
        prompt: 'Find menu items priced above the average menu price.',
        hint: 'A subquery in the WHERE clause: WHERE price > (SELECT AVG(price) ...).',
        lesson: [
          "A subquery is a SELECT statement nested inside another query — it runs first, and its result gets used by the outer query.",
          '(SELECT AVG(price) FROM menu_items) computes the average price on its own, returning a single number — exactly the shape WHERE needs to compare against.',
          "WHERE price > (SELECT AVG(price) FROM menu_items) then compares each row's price against that single computed average, keeping only the rows priced above it.",
          'SELECT name, price FROM menu_items WHERE price > (SELECT AVG(price) FROM menu_items); — the subquery runs once, SQLite computes the average ($6.865), and only items priced above that make the cut.',
        ],
        starterQuery: 'SELECT name, price FROM menu_items;',
        type: 'select',
        expected: [
          ['Espresso Beans (1kg)', 18.0],
          ['Gift Card', 25.0],
        ],
      },
      {
        id: 'p3-2',
        title: 'Regulars',
        prompt: 'Which customers have placed more than 1 order? Show name and order count.',
        hint: 'JOIN + GROUP BY customer, then HAVING COUNT(*) > 1.',
        lesson: [
          'orders only stores a customer_id number, not a name — to show a readable name, you need to JOIN it to the customers table where the name actually lives.',
          'JOIN customers ON orders.customer_id = customers.id lines up each order with the matching customer row, based on that shared id.',
          'GROUP BY customers.name then buckets the joined rows by customer, and COUNT(*) counts how many orders landed in each bucket.',
          "HAVING COUNT(*) > 1 keeps only the customers whose bucket has more than one order — the 'regulars'. Full query: SELECT customers.name, COUNT(*) FROM orders JOIN customers ON orders.customer_id = customers.id GROUP BY customers.name HAVING COUNT(*) > 1;",
        ],
        starterQuery: 'SELECT customers.name, COUNT(*)\nFROM orders\nJOIN customers ON orders.customer_id = customers.id\nGROUP BY customers.name;',
        type: 'select',
        expected: [
          ['Alice', 2],
          ['Bob', 2],
        ],
      },
      {
        id: 'p3-3',
        title: 'Silent Customers',
        prompt: 'List customers who have never left a review.',
        hint: 'NOT EXISTS (SELECT 1 FROM reviews WHERE reviews.customer_id = customers.id).',
        lesson: [
          "EXISTS checks whether a subquery returns any rows at all — it doesn't care what the rows contain, only whether there are any.",
          'NOT EXISTS flips that check: it\'s true only when the subquery returns nothing at all.',
          'The subquery SELECT 1 FROM reviews WHERE reviews.customer_id = customers.id is correlated — for each customer row being checked, it looks for any review with a matching customer_id.',
          'SELECT name FROM customers WHERE NOT EXISTS (SELECT 1 FROM reviews WHERE reviews.customer_id = customers.id); keeps only customers for whom that inner search comes up completely empty — customers with zero reviews.',
        ],
        starterQuery: 'SELECT name FROM customers;',
        type: 'select',
        expected: [['Carla'], ['Elena']],
      },
    ],
  },
  {
    id: 'high-score',
    title: 'High Score Mechanics',
    subtitle: 'game_sessions',
    tables: ['game_sessions'],
    description: 'Rank plays and compare scores with window functions and CTEs.',
    challenges: [
      {
        id: 'p4-1',
        title: 'Pixel Runner Leaderboard',
        prompt: 'Rank every Pixel Runner play by score, highest first.',
        hint: 'RANK() OVER (ORDER BY score DESC).',
        lesson: [
          "Window functions, like RANK(), compute a value across a set of rows without collapsing them into one summary row the way GROUP BY does — every row stays visible.",
          'OVER (ORDER BY score DESC) tells RANK() how to number the rows: highest score gets rank 1, next-highest gets rank 2, and so on.',
          "SELECT customer_id, score, RANK() OVER (ORDER BY score DESC) FROM game_sessions WHERE game_name = 'Pixel Runner'; keeps every individual play, but adds a running rank column next to each one.",
          'This is the key difference from ORDER BY alone: ORDER BY just sorts the rows, while RANK() actually assigns and returns a rank number you can select, filter, or compare later.',
        ],
        starterQuery: "SELECT customer_id, score FROM game_sessions WHERE game_name = 'Pixel Runner';",
        type: 'select',
        expected: [
          [1, 1400, 1],
          [1, 1200, 2],
          [2, 950, 3],
          [6, 700, 4],
        ],
      },
      {
        id: 'p4-2',
        title: "Everyone's Best Run",
        prompt: "Find each player's best score per game, using a CTE.",
        hint: 'WITH ranked AS (... ROW_NUMBER() OVER (PARTITION BY customer_id, game_name ORDER BY score DESC) ...) SELECT ... WHERE rn = 1.',
        lesson: [
          'A CTE (Common Table Expression) is a named, temporary result set defined with WITH — it lets you build a query in readable stages instead of nesting subqueries.',
          'PARTITION BY customer_id, game_name resets the numbering for each unique player+game combination — think of it as GROUP BY, but for window functions, without collapsing rows.',
          "ROW_NUMBER() OVER (PARTITION BY customer_id, game_name ORDER BY score DESC) numbers each player's plays of a game from 1 (their best score) upward, restarting at 1 for every new player/game pair.",
          "WITH ranked AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY customer_id, game_name ORDER BY score DESC) AS rn FROM game_sessions) SELECT customer_id, game_name, score FROM ranked WHERE rn = 1; — the outer query then just keeps the rows where rn = 1, i.e. each player's single best run per game.",
        ],
        starterQuery: 'SELECT customer_id, game_name, score FROM game_sessions;',
        type: 'select',
        expected: [
          [1, 'Pixel Runner', 1400],
          [2, 'Pixel Runner', 950],
          [3, 'Bean Blitz', 800],
          [4, 'Bean Blitz', 1100],
          [6, 'Pixel Runner', 700],
        ],
      },
      {
        id: 'p4-3',
        title: 'Game Records',
        prompt: "What's the top score for each game?",
        hint: 'GROUP BY game_name with MAX(score).',
        lesson: [
          'This is the same GROUP BY + aggregate pattern from Phase 2, applied to a new table: bucket the rows, then summarize each bucket.',
          'GROUP BY game_name buckets every play by which game it belongs to — all Pixel Runner sessions together, all Bean Blitz sessions together.',
          'MAX(score) then finds the single highest score within each bucket, discarding every other play in that bucket.',
          'SELECT game_name, MAX(score) FROM game_sessions GROUP BY game_name; — one row per game, showing only that game\'s all-time top score.',
        ],
        starterQuery: 'SELECT game_name, score FROM game_sessions;',
        type: 'select',
        expected: [
          ['Bean Blitz', 1100],
          ['Pixel Runner', 1400],
        ],
      },
    ],
  },
  {
    id: 'master-barista',
    title: 'Master Barista Boss Level',
    subtitle: 'employees, customers, reviews',
    tables: ['employees'],
    description: 'The finale: self-joins, a recursive CTE org chart, and a multi-condition combo.',
    challenges: [
      {
        id: 'p5-1',
        title: 'Chain of Command',
        prompt: "List each employee with their manager's name.",
        hint: 'Self-join employees to itself on manager_id = id.',
        lesson: [
          "A self-join is a JOIN where a table is joined to itself — useful when a table's rows reference other rows in the same table, like employees pointing to their own manager.",
          'Because both \'copies\' of the table are the same employees table, you need aliases (e.g. e and m) to tell SQLite which copy you mean at each point in the query.',
          'Joining e.manager_id = m.id lines up each employee (e) with the row (m) whose id matches their manager_id — that row is their manager.',
          'SELECT e.name, m.name FROM employees e JOIN employees m ON e.manager_id = m.id; — for every employee with a manager, this returns their name next to their manager\'s name. (Coco has no manager, so a plain JOIN would drop her — that\'s a tradeoff of INNER JOIN worth noticing.)',
        ],
        starterQuery: 'SELECT e.name, e.manager_id FROM employees e;',
        type: 'select',
        expected: [
          ['Coco', null],
          ['Kiki', 'Coco'],
          ['Mimi', 'Kiki'],
        ],
      },
      {
        id: 'p5-2',
        title: "Mimi's Reporting Line",
        prompt: "Show the full management chain starting from Mimi, all the way to the top.",
        hint: 'WITH RECURSIVE chain AS (base case: Mimi UNION ALL recursive step joining to the manager) SELECT ...',
        lesson: [
          'A recursive CTE is a WITH block that refers to itself — it repeats a query step over and over, each time building on the previous result, until it runs out of new rows to add.',
          "It has two parts glued together with UNION ALL: a base case (the starting row) and a recursive step (how to find the 'next' row from the current one).",
          "Base case: WITH RECURSIVE chain AS (SELECT * FROM employees WHERE name = 'Mimi') — this seeds the recursion with Mimi herself.",
          'Recursive step: UNION ALL SELECT e.* FROM employees e JOIN chain c ON e.id = c.manager_id) — each pass looks up the manager of whoever was just added, and keeps going until it reaches someone with no manager (manager_id IS NULL), building the full chain from Mimi up to the owner.',
        ],
        starterQuery: 'SELECT name, manager_id FROM employees;',
        type: 'select',
        expected: [
          ['Mimi', 0],
          ['Kiki', 1],
          ['Coco', 2],
        ],
      },
      {
        id: 'p5-3',
        title: 'The Perfect Cup',
        prompt: 'Which gold-tier customers left a 5-star review? Show their name and the review comment.',
        hint: 'JOIN customers to reviews, filter membership_tier and rating together.',
        lesson: [
          'This combines two skills from earlier: JOIN to connect related tables, and multiple WHERE conditions with AND to filter on more than one thing at once.',
          'JOIN customers ON reviews.customer_id = customers.id connects each review back to the customer who wrote it, so you can filter and display customer fields like name and membership_tier.',
          "WHERE customers.membership_tier = 'gold' AND reviews.rating = 5 then keeps only rows that pass both checks — the customer has to be gold tier AND the review has to be a 5-star rating.",
          "SELECT customers.name, reviews.comment FROM customers JOIN reviews ON reviews.customer_id = customers.id WHERE customers.membership_tier = 'gold' AND reviews.rating = 5; — putting it all together finds exactly the customers who are both top-tier members and left a perfect review.",
        ],
        starterQuery: 'SELECT customers.name, reviews.comment\nFROM customers\nJOIN reviews ON reviews.customer_id = customers.id;',
        type: 'select',
        expected: [
          ['Alice', 'Best latte in town!'],
          ['Dev', 'Great gift idea'],
        ],
      },
    ],
  },
];

export const ALL_CHALLENGES = PHASES.flatMap((phase) =>
  phase.challenges.map((challenge) => ({ ...challenge, phaseId: phase.id, phaseTitle: phase.title }))
);

export function getChallengeById(id) {
  return ALL_CHALLENGES.find((c) => c.id === id);
}

export function getNextChallengeId(id) {
  const idx = ALL_CHALLENGES.findIndex((c) => c.id === id);
  if (idx === -1 || idx === ALL_CHALLENGES.length - 1) return null;
  return ALL_CHALLENGES[idx + 1].id;
}

// Tables unlock cumulatively as phases progress, so a beginner on Phase 1
// only ever sees menu_items — not the full schema — in the database viewer.
export function getVisibleTables(phaseId) {
  const idx = PHASES.findIndex((p) => p.id === phaseId);
  if (idx === -1) return [];
  const seen = new Set();
  for (let i = 0; i <= idx; i++) {
    PHASES[i].tables.forEach((t) => seen.add(t));
  }
  return [...seen];
}
